routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('employee', EmployeeController::class);
Route::resource('company', CompanyController::class);

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    protected $table = 'employee';
    protected $fillable = [
        'nama',
        'atasan_id',
        'company_id'
    ];

    // public function present_nama_atasan(){
    //     return $this->find($this->atasan_id)->nama;
    // }
    // public function present_nama_company(){
    //     $company = $this->company;
    //     return $company->nama;
    // }
    public function bawahan(){
        return $this->hasMany(self::class,'atasan_id');
    }
    public function atasan(){
        return $this->belongsTo(self::class,'atasan_id');
    }
    public function company(){
        return $this->BelongsTo('App\Models\Company','company_id');
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Company;
use App\Models\Employee;

use Illuminate\Http\Request;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employee = Employee::all();
        // dd($employee->atasan()->nama);
        return view('employee.index',['employee' => $employee]);
    }
    private function _validate(Request $request){
        $validatedData = $request->validate([
            'nama' => 'required|min:2|max:50'
        ]);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $company = Company::all();
        $atasan = Employee::all();
        return view('employee.create',['company' => $company,'atasan' => $atasan]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $all = $request->all();
        $this->_validate($request);
        if ($request->input('atasan_id')=='null') {
            unset($all['atasan_id']);
        }
        Employee::create($all);
        return redirect()->route('employee.index')->with('success','Data Berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company = Company::all();
        $atasan = Employee::all();

        $employee = Employee::find($id);
    return view('employee.edit',['employee' => $employee,'company' => $company,'atasan' => $atasan]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $all = $request->all();
        $this->_validate($request);
        $employee = Employee::find($id);
        if ($all['atasan_id']=='null') {
            unset($all['atasan_id']);
        }
        $employee->update($all);
        return redirect()->route('employee.index')->with('success','Data Berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $employee = Employee::find($id);
        $employee->delete();
        return redirect()->route('employee.index')->with('success','Data Berhasil dihapus');
    }
}

resources/views/employee/create.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Form Employee</title>
    <link rel="stylesheet" href="/css/employee/create.css">
</head>

<body>
    <form action="{{ route('employee.store') }}" method="POST">
        <h1>Tambah Employe</h1>
        @csrf
        <label for="nama">Nama :</label>
        <input type="text" id="nama" name="nama" placeholder="Masukkan nama">
        <label for="atasan">Atasan :</label>
        <select name="atasan_id" id="atas">
            <option value="null">Tidak memiliki atasan</option>
            @foreach ($atasan as $item)
            <option value="{{ $item->id }}">{{ $item->nama }}</option>
            @endforeach
        </select>
        <label for="company">Company :</label>
        <select name="company_id" id="atas">
            @foreach ($company as $item)
            <option value="{{ $item->id }}">{{ $item->nama }}</option>
            @endforeach
        </select>
        <div>
            <a href="{{ route('employee.index') }}" class="btn btn-back">Back</a>
            <button type="submit" class="btn btn-simpan" value="simpan">Submit</button>
        </div>
    </form>

    <!-- {{--  Js  --}}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
        crossorigin="anonymous"></script> -->
</body>

</html>

resources/views/employee/edit.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Employee</title>
    <link rel="stylesheet" href="/css/employee/edit.css">
</head>

<body>
    <form action="{{ route('employee.update',$employee->id) }}" method="POST">
        <h1>Tambah Employe</h1>
        @csrf
        @method('put')
        <label for="nama">Nama :</label>
        <input type="text" id="nama" class="form-control" name="nama" value="{{$employee->nama}}">
        <label for="atasan">Atasan :</label>
        <select name="atasan_id" class="form-control" id="atas">
            <option value="null">tidak memiliki atasan</option>
            @foreach ($atasan as $item)
            <option @if ($employee->atasan_id == $item->id)
                selected
                @endif value="{{ $item->id }}">{{ $item->nama }}</option>
            @endforeach
        </select>
        <label for="company">Company :</label>
        <select name="company_id" id="atas" class="form-control">
            @foreach ($company as $item)
            <option @if ($employee->company_id == $item->id)
                selected
                @endif value="{{ $item->id }}">{{ $item->nama }}</option>
            @endforeach
        </select>
        <div>
            <a href="{{ route('employee.index') }}" class="btn btn-back">Back</a>
            <button type="submit" class="btn btn-simpan" value="simpan">Simpan</button>
        </div>
    </form>
</body>

</html>

resources/views/employee/index.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Employee</title>
    <link rel="stylesheet" href="/css/employee/index.css">
</head>

<body>
    <div class="card">
        <h3 class="m-0 p-0">List Employes</h3>
        @if ($message = Session::get('success'))
        <div class="info">
            {{$message}}
        </div>
        @endif
        <table>
            <thead>
                <tr>
                    <th>no</th>
                    <th>nama</th>
                    <th class="text-center">atasan</th>
                    <th class="text-center">company</th>
                    <th class="text-center" style="width: 200px">aksi</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($employee as $no => $item)
                <tr>
                    <td>{{ $no+1 }}</td>
                    <td>{{ $item->nama }}</td>
                    @if ($item->atasan)
                    <td>{{ $item->atasan->nama }}</td>
                    @else
                    <td>-</td>
                    @endif
                    <td>{{ $item->company->nama }}</td>
                    <td>
                        <a href="{{ route('employee.edit', $item->id) }}" class="btn btn-edit">Edit</a>
                        <form action="{{ route('employee.destroy', $item->id) }}" method="POST">
                            @csrf
                            <input type="hidden" name="_method" value="delete" />
                            <input type="submit" class="btn btn-hapus" value="Hapus">
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        <a href="{{ route('employee.create') }}" class="btn btn-tambah">Tambah</a>
    </div>
</body>

</html>