routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('employee', EmployeeController::class);
Route::resource('company', CompanyController::class);

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    protected $table = 'company';
    protected $fillable = [
        'nama',
        'alamat'
    ];
    public function employee(){
        return $this->hasOne('\App\Models\Employee','company_id');
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Models\Company;
use App\Models\Employee;
use Illuminate\Http\Request;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $company = Company::all();
        return view('company.index',['company'=>$company]);
    }
    private function _validate(Request $request){
        $validatedData = $request->validate([
            'nama' => 'required|min:2|max:50',
            'alamat' => 'required|min:2|max:50'
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('company.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $company = $request->all();
        $this->_validate($request);

        Company::create($company);
        return redirect()->route('company.index')->with('success','Data Berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company = Company::find($id);
        return view('company.edit',['company' => $company]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->_validate($request);
        $company = Company::find($id);
        $company->update($request->all());
        return redirect()->route('company.index')->with('success','Data Berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $company = Company::find($id);
        $company->delete();
        return redirect()->route('company.index')->with('success','Data Berhasil dihapus');
    }
}

resources/views/company/create.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tambah Company</title>
    <link rel="stylesheet" href="/css/company/create.css">
</head>

<body>
    <form action="{{ route('company.store') }}" method="POST">
        <h1>Form Company</h1>
        @csrf
        <label for="nama">Nama :</label>
        <input type="text" id="nama" class="form-control" name="nama" placeholder="Masukkan nama">
        <label for="alamat">Alamat :</label>
        <input type="text" id="alamat" class="form-control" name="alamat" placeholder="Masukkan alamat">
        <div>
            <a href="{{ route('company.index') }}" class="btn btn-back">Back</a>
            <button type="submit" class="btn btn-simpan" value="simpan">simpan</button>
        </div>
    </form>
</body>

</html>

resources/views/company/edit.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Company</title>
    <link rel="stylesheet" href="/css/company/edit.css">
</head>

<body>
    <form action="{{ route('company.update',$company->id) }}" method="POST">
        <h1>Edit Company</h1>
        @csrf
        @method('put')
        <label for="nama">Nama :</label>
        <input type="text" id="nama" name="nama" value="{{$company->nama}}" />
        <label for="">Alamat</label>
        <input type="text" name="alamat" placeholder="Alamat" value="{{$company->alamat}}">
        <div>
            <a href="{{ route('company.index') }}" class="btn btn-back">Back</a>
            <button type="submit" class="btn btn-simpan" value="simpan">Simpan</button>
        </div>
    </form>
</body>

</html>

resources/views/company/index.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Company</title>
    <link rel="stylesheet" href="/css/company/index.css">
</head>

<body>
    <div class="card">
        <h3>List Company</h3>
        @if ($message = Session::get('success'))
        <div class="info">
            {{$message}}
        </div>
        @endif
        <table>
            <thead>
                <tr>
                    <th>no</th>
                    <th>nama</th>
                    <th>alamat</th>
                    <th>aksi</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($company as $no => $item)
                <tr>
                    <td>{{ $no+1 }}.</td>
                    <td>{{ $item->nama }}</td>
                    <td>{{ $item->alamat }}</td>
                    <td>
                        <a href="{{ route('company.edit', $item->id) }}" class="btn btn-edit">Edit</a>
                        <form action="{{ route('company.destroy', $item->id) }}" method="POST">
                            @csrf
                            <input type="hidden" name="_method" value="delete" />
                            <input type="submit" class="btn btn-hapus" value="Hapus">
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        <a href="{{ route('company.create') }}" class="btn btn-tambah">Tambah</a>
    </div>
</body>

</html>